name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Debug repository name and token
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "Repository from context: ${{ github.repository }}"
          echo "Checking GitHub token access..."
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/user

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
